const express = require('express');
const router = express.Router();
const { requireAuth } = require("../../utils/auth.js");
const { Spot, Review, SpotImage, User, Sequelize, ReviewImage, Booking } = require("../../db/models")
const { check } = require('express-validator');
const { handleValidationErrors } = require('../../utils/validation');
const { Op } = require('sequelize')

//   const validateBooking = [
//     check('endDate').valueOf()
//       .exists({ checkFalsy: true })
//       .isAfter('startDate').valueOf()
//       .withMessage('endDate cannot come before startDate'),
//       handleValidationErrors
//   ];
router.get('/current',requireAuth, async (req, res, next) => {
    let userBookings;
    userBookings = await Booking.findAll({
        where: {
            userId: req.user.id,
        },
        attributes: {
            include: ['id']
        },
        include: [
        {
            model: Spot,
            attributes: {
                exclude: ['description', 'createdAt', 'updatedAt']
            },
            include: {
                model:SpotImage,
                attributes: [['url', 'previewImage']],
            }
        }]
    })
    userBookings = userBookings.map(userBooking => {
        const jsonSpot = userBooking.toJSON();
        if (jsonSpot.Spot.SpotImages[0]) {
            jsonSpot.previewImage = jsonSpot.Spot.SpotImages[0].previewImage;
          } else {
            jsonSpot.previewImage = null;
          }
          delete jsonSpot.Spot.SpotImages
        return jsonSpot;
      });
      res.json({Bookings: userBookings});
})

router.put('/:bookingId', requireAuth, async (req, res, next) => {
    let updatedBooking;
    updatedBooking = await Booking.findOne({
        where: {
            id: req.params.bookingId
        },
        limit: 1,
        attributes: {
            include: ['id']
        }
    })
    if (updatedBooking === null) {
        return res
            .status(404)
            .json({
                "message": "Booking couldn't be found"
            })
    }
    if (updatedBooking.endDate < new Date()) {
        return res.status(403).json({
            message: "Past bookings can't be modified"
        })
    }
    const conflictBooking = await Booking.findOne({
        where: {
            spotId: updatedBooking.spotId,
            [Op.or]: [{startDate:{[Op.between]:[req.body.startDate,req.body.endDate]}},
            {endDate:{[Op.between]:[req.body.startDate,req.body.endDate]}}]
        },
        limit: 1
    });
    if (conflictBooking) {
        return res.status(403).json({
            message: "Sorry, this spot is already booked for the specified dates",
            errors: {
              startDate: "Start date conflicts with an existing booking",
              endDate: "End date conflicts with an existing booking"
            }
          })
        }
    try {
        await updatedBooking.update(req.body)
        res.json(updatedBooking)
    } catch(err) {
        if (err.name === 'SequelizeValidationError') {
            return res
                .status(400)
                .json({
                    message: "Bad Request", // (or "Validation error" if generated by Sequelize),
                    errors: {
                        endDate: "endDate cannot be on or before startDate"
                    }
                })
        }
        else {
            res
                .status(500)
                .json({
                    message: err.message
                })
        }
    }
});

router.delete('/:bookingId', requireAuth, async (req, res, next) => {
    const deletedBooking = await Booking.findOne({
        where: {
            id: req.params.bookingId
        },
        attributes: {
            include: ['id']
        },
        include: {
            model: Spot
        }
    })
    if (new Date() > deletedBooking.startDate) {
        return res.status(403).json({
            message: "Bookings that have been started can't be deleted"
        })
    }
    if (deletedBooking === null) {
        return res.status(404).json({
            "message": "Spot couldn't be found"
          })
    }
    if (deletedBooking.userId === req.user.id || deletedBooking.Spot.ownerId === req.user.id) {
        await deletedBooking.destroy()
        return res.json({
            "message": "Successfully deleted"
          })
    }
    res.status(404).json({
        "message": "You don't have authorization to delete this spot"
      })
})
module.exports = router;
